server:
  port: 8070

spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      routes: # 路由策略,
        - id: config_route
          predicates:
          - Path=/gateway/**
          filter:
            - StripPrefix=1 # 填过前缀访问
          uri: http://localhost:8088/
        - id: cookie_route
          predicates:  # nginx  location ~
            - Cookie=name,cy
#            - Path=/define/**
#            - Auth=Authorization,token
          filters:
            - StripPrefix=1
          uri: https://www.gupaoedu.com


eureka:
  client:
    service-url:
      defaultZone: http://localhost:9999/eureka